name: BetterLottery-Reloaded
version: 0.0.1
main: cn.xtuly.mcp.betterlotteryreloaded.BetterLotteryReloaded
authors: [AmemiyaSigure,DoraLY]
description: A reloaded version of BetterLottery
website: xtuly.cn
commands:
  bl:
    permission: bl.admin
permissions:
  bl.use:
    default: not op
  bl.admin:
    default: op